### Admin Login
POST http://localhost:3002/login/admin
Content-Type: application/json

{
  "username":"YOMOMCYBERCAFE",
  "password":"donottrythisathome69"
}

### Update Computer
PUT http://localhost:3002/update/computer/computer_name
Content-Type: application/json
Authorization: Bearer 

{
  "systemworking": "yes",
  "available": "true"
}

### Get Available Cabins
GET http://localhost:3002/available/cabins
Authorization: Bearer 

### Create Member
POST http://localhost:3002/create/member
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllPTU9NQ1lCRVJDQUZFIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0MTIzMTYxLCJleHAiOjE3MDQxMjM3NjF9.iRE1HSzS4lJKgnSWKyDR8ZtNmG71-C1AKDQDfXWAFIE

{
  "customername": "member_username",
  "idproof": "member_id_proof",
  "password": "member_password"
}

### Member Login
POST http://localhost:3002/login/member
Content-Type: application/json

{
  "idproof": "member_id_proof",
  "password": "member_password"
}

### Get Members (Admin Only)
GET http://localhost:3002/get/members
Authorization: Bearer 

### Create Visitor
POST http://localhost:3002/create/visitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHByb29mIjoibWVtYmVyX2lkX3Byb29mIiwicm9sZSI6Im1lbWJlciIsImlhdCI6MTcwNDEyMzIzNSwiZXhwIjoxNzA0MTIzODM1fQ.-JFhCsgcVeslPGrFoy9dlvA63NRXuDNzJck1arUx9Ps

{
  "CreatedBy": "member_username",
  "visitorname": "visitor_name",
  "idproof": "visitor_id_proof"
}

### Get My Visitors
GET http://localhost:3002/get/my-visitors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHByb29mIjoibWVtYmVyX2lkX3Byb29mIiwicm9sZSI6Im1lbWJlciIsImlhdCI6MTcwNDEyMzk0NywiZXhwIjoxNzA0MTI0NTQ3fQ.TINkr3zH2WkgEWsGaqPEjI_trqk6hNHfZfkR2xKgGbo

### Get Online Customers (Admin Only)
GET http://localhost:3002/online/customer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllPTU9NQ1lCRVJDQUZFIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0MTIzMTYxLCJleHAiOjE3MDQxMjM3NjF9.iRE1HSzS4lJKgnSWKyDR8ZtNmG71-C1AKDQDfXWAFIE

### View Computer Configuration (Admin Only)
GET http://localhost:3002/view/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllPTU9NQ1lCRVJDQUZFIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0MTIzMTYxLCJleHAiOjE3MDQxMjM3NjF9.iRE1HSzS4lJKgnSWKyDR8ZtNmG71-C1AKDQDfXWAFIE
